### ISSUE TITLE
CodeDeploy failing to run install_dependencies.sh due to missing +x?

### ISSUE THREAD

**Issue by Renari** [aws/aws-codedeploy-agent#162]
appspec.yml
```
version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
```
Error in log:

```
2018-05-16 14:38:47 ERROR [codedeploy-agent(15536)]: InstanceAgent::Plugins::CodeDeployPlugin::CommandPoller: Error during perform: InstanceAgent::Plugins::CodeDeployPlugin::ScriptError - Script does not exist at specified location: /opt/codedeploy-agent/deployment-root/76190bb7-1987-4ac1-aaef-865b7e8c8ac2/d-B6OS6OA6T/deployment-archive/scripts/install_dependencies.sh - /opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/hook_executor.rb:118:in `block (2 levels) in execute'
```
Contents of scripts directory at above path:
```
ubuntu@ip-*-*-*-*:/opt/codedeploy-agent/deployment-root/76190bb7-1987-4ac1-aaef-865b7e8c8ac2/d-B6OS6OA6T/deployment-archive/scripts$ ls -l
total 12
-rw-r--r-- 1 root root 258 May 16 14:38 build-admesh.sh
-rw-r--r-- 1 root root 546 May 16 14:38 install-dependencies.sh
-rw-r--r-- 1 root root 837 May 16 14:38 provision.sh
```
