### ISSUE TITLE
Unable to pass argument to the AppSpec Hooks

### ISSUE THREAD

**Issue by shankar-moeng** [aws/aws-codedeploy-agent#179]
Currently, I don't see any option to pass argument to the shell script. The AWS documentation does not have any relavent example. For Ex:- 

```
ApplicationStart:
    - location: scripts/worker_start.sh <argument>
       timeout: 300
       runas: root
```

Is there any way to pass argument or can it be considered as feature request?
