### ISSUE TITLE
Add support for excluding directories in appspec.yml "Permissions" section

### ISSUE THREAD

**Issue by swekaj** [aws/aws-codedeploy-agent#27]
I would like the ability (or clarification on how) to exclude sub-directories and their contents in the permissions section of the `appspec.yml`.

Given I have a file structure

```
/tmp/test
├── file1
├── folder1
└── folder2
    ├── file2
    └── folderA
        ├── folderI
        └── folderII
```

I would like to create an `appspec.yml` file with the following section:

```
permissions:
  - origin: /tmp/test
    owner: user1
    group: group1
    exclude: [ folder2/folderA ]
    mode: 644
  - origin: /tmp/test/folder2/folderA
    mode: 664
    owner: user1
    group: group1
```

This would set the mode for all files and folder under `/tmp/test` except for those in `/tmp/test/folder2/folderA` to 644, while all files and folders under `/tmp/test/folder2/folderA` have a mode of 664.

Currently, when I try this I get an error saying `/tmp/test/folder2/folderA/folderI` has duplicate permission setting instructions.
