### ISSUE TITLE
Facing issue in "file_exists_behavior: RETAIN" in Appsec file  

### ISSUE THREAD

**Issue by prakashraju619** [aws/aws-codedeploy-agent#340]
I have updated the **appsec** file `"file_exists_behavior: RETAIN"` in my case whenever there in change source (github) it has to be    update or replace particular files in destination folder, but i can see all the files are updating or replacing happening

```
version: 0.0
os: Windows
files:
  - source: /
    destination: C:\xxx
  
file_exists_behavior: RETAIN
```
