### ISSUE TITLE
Run codedeploy-agent as non-root user

### ISSUE THREAD

**Issue by Jud** [aws/aws-codedeploy-agent#5]
It would be nice to be able to run the agent as a non-root user, or, only run the supervisor as root, and drop privileges on the child process if they're not needed.

In our case, we'd like to only deploy signed binaries which are checked by a server agent as part of the deploy process (with the agent only decrypting a payload if the signatures are verified). Because code-deploy runs as root, it is possible that compromised credentials could lead to an unauthorized payload being deployed.

**Comment by todwilli** [comment]
You can use the AppSpec file to set the runas user for scripts as well as set the permissions on installed files. A combination of the two should cover your use case. 

Check out http://docs.aws.amazon.com/codedeploy/latest/userguide/app-spec-ref.html#app-spec-ref-hooks and http://docs.aws.amazon.com/codedeploy/latest/userguide/app-spec-ref.html#app-spec-ref-permissions for more details as well as examples.

**Comment by Jud** [comment]
@todwilli This will cover the use case, but I'm still a bit weary about needing to run a remote-code-fetching daemon as root. Seems like a large attack surface area relative to whatever convenience is gained.

**Comment by wmbutler** [comment]
@todwilli 

Within my appspec.yml file, I'm setting the runas to ubuntu. The problem is that my source directory is entirely owned by root. I've attempted to change the permissions of the source directory where the script is located and I keep getting the same 

.....deployment-archive/./server.sh: Permission denied

Here is my appspec.yml file (I've tried both `.` and `./` to set the user on the `server.sh` script.

```
version: 0.0
os: linux
files:
  - source: dist
    destination: /home/test/dist
  - source: node_modules
    destination: /home/test/node_modules
  - source: server.json
    destination: /home/test
permissions:
  - object: /home/test
    owner: ubuntu
    group: ubuntu
permissions:
  - object: .
    owner: ubuntu
    group: ubuntu
hooks:
  ApplicationStart:
    - location: ./server.sh
      timeout: 30
      runas: ubuntu
```
