### ISSUE TITLE
retry(wait) options for ValidateService hook

### ISSUE THREAD

**Issue by quiver** [aws/aws-codedeploy-agent#56]
It can take a while before processes are ready to respond requests, but there's no retry(wait) concept for `ValidateService` hook of `appspec.yml`. So you need to write your own poll-until-apps-are-ready logics.

So it would be great if you can write something like ::

```
  ValidateService:
    - location: Scripts/MonitorService.sh
      timeout: 3600
      retry: 5
      retry_interval: 30
      runas: codedeployuser
```

and put only the core logic to `ValidateService` scripts
